
@BASE_URL=http://localhost:3000
### Register User

POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
  "username": "Looma_user",
  "email": "looma@test",
  "password": "loomatest"
}

### Login User

POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
 "email": "looma@test",
  "password": "loomatest"
}

### Check the token and allow access

GET {{BASE_URL}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjFlYTBkMzU2ODhlNjFkNDU3OWY5YyIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoidG9uaTEyMyIsImlhdCI6MTc2MDc3NjQyMn0.O7fdxfXt8YinIcxEFhAiLWBGhaRdbUR7nyucWx6ShiY

### Removes token from the cookie
POST {{BASE_URL}}/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjFlYTBkMzU2ODhlNjFkNDU3OWY5YyIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoidG9uaTEyMyIsImlhdCI6MTc2MDc3NjQyMn0.O7fdxfXt8YinIcxEFhAiLWBGhaRdbUR7nyucWx6ShiY
