@BASE_URL=http://localhost:3000


@TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjM2NTQ4MzZiYjFlNWRiYzg2YWMxMCIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoiVG9uaSIsImlhdCI6MTc2MDk2NzA4MH0.75t3ZyM1DXUyhuKWevsCR_vBRWUw7qBg74Qf8CmEarU

### Create chat by FriendId
POST {{BASE_URL}}/api/chats
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "friendId":"68e7ad64b40c24c8918e4e05"
}

### Send a message 

POST {{BASE_URL}}/api/chats/68fb3bec1433455b77968ba3/messages
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "content":"Hi"
}


### Create group chat 
POST {{BASE_URL}}/api/chats/groups
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


{
  "name":"Frontend Mentors",
  "participants": ["68f0e6522bcb05c85e0c529e","68f0e83a2bcb05c85e0c5356"]
}

### Get group chats
GET {{BASE_URL}}/api/chats/groups
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Find chat by user id
GET {{BASE_URL}}/api/chats/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Find all chats

GET {{BASE_URL}}/api/chats
Content-Type: application/json

### Delete chat by ID
@CHAT_ID=68f255f7fa8d51b323c9577e
DELETE {{BASE_URL}}/api/chats/{{CHAT_ID}}
Content-Type: application/json


### Get group chat based on chat Id
GET {{BASE_URL}}/api/chats/68f8ea9e53d8061193dc5db4/groups

### Get chat based on id 
GET {{BASE_URL}}/api/chats/68f768aff70537020bf6f19e