@BASE_URL=http://localhost:3000


@TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjM2NTQ4MzZiYjFlNWRiYzg2YWMxMCIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoiVG9uaSIsImlhdCI6MTc2MDk2NzA4MH0.75t3ZyM1DXUyhuKWevsCR_vBRWUw7qBg74Qf8CmEarU

### Create chat by FriendId
POST {{BASE_URL}}/chats
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "friendId": "68e7ad64b40c24c8918e4e05"
}

### Create group chat 
POST {{BASE_URL}}/chats/group
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


{
  "name":"Frontend Mentors",
  "participants": ["68f0e6522bcb05c85e0c529e","68f0e83a2bcb05c85e0c5356"]
}

### Get group chats
POST {{BASE_URL}}/chats/group/all
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Find chat by user id
GET {{BASE_URL}}/chats/user
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Find all chats

GET {{BASE_URL}}/chats/all
Content-Type: application/json

### Delete chat by ID
@CHAT_ID=68f117fe285f9fb1749de411
DELETE {{BASE_URL}}/chats/delete/{{CHAT_ID}}
Content-Type: application/json


### Get group chat based on chat Id
GET {{BASE_URL}}/chats/group/68f64c257cd0ff35b409aa25

### Get chat based on id 
GET {{BASE_URL}}/chats/68f768aff70537020bf6f19e