@BASE_URL=http://localhost:3000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjBlNjYxMmJjYjA1Yzg1ZTBjNTJhNSIsImVtYWlsIjoidG9uaUBleGFtLmNvbSIsInVzZXJuYW1lIjoidG9uaSIsImlhdCI6MTc2MDYxODA5NX0.At-RXeJR83thDJw_efVkluY3HM4m-6s6eBV9gOcuWVg

### Register User

POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "username": "toni",
  "email": "toni@exam.com",
  "password": "strongpassword"
}

### Login User

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
 "email": "toni@exam.com",
  "password": "strongpassword"
}

### Get all users

GET {{BASE_URL}}/user/others
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Add friend to a user
POST {{BASE_URL}}/user/friends/add
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "friendId":"68e6994f72cc05181b3ae7fb"
}


### Remove friend from a user

DELETE {{BASE_URL}}/user/friends/remove/68e6994f72cc05181b3ae7fb
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### Get all user Friends

GET {{BASE_URL}}/user/friends/all
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
